"""add change archive fields

Revision ID: f1fd82b538a1
Revises: d1bbbe29df8d
Create Date: 2025-09-25 00:25:42.189262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fd82b538a1'
down_revision: Union[str, Sequence[str], None] = 'd1bbbe29df8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'milestones', ['milestone'], ['milestone'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.drop_column('archived_at')
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
